name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: version-checking
      run: gcc -v && g++ -v && cmake --version
    - name: cmake-configure
      run: cmake -H. -B.build -DCMAKE_BUILD_TYPE=Debug -D version=v0.0.0-github-build
    - name: cmake-build
      run: cmake --build .build
    - name: cmake-test
      run: cd .build && ctest
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
